all: generate-iso-projection

generate-iso-projection: generate-iso-projection.o
	gcc generate-iso-projection.o -o generate-iso-projection

generate-iso-projection.o: generate-iso-projection.c
	gcc generate-iso-projection.c -c
